server:
  port: 8080

logging:
  level:
    root: INFO
    io:
      sapl: DEBUG
    org:
      springframework:
        web: INFO
        security: TRACE


spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          miskatonic-client-oidc:
            provider: spring
            client-id: miskatonic-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: miskatonic-client-oidc
          miskatonic-client-authorization-code:
            provider: spring
            client-id: miskatonic-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: books.read,faculty.read,bestiary.read
            client-name: miskatonic-client-authorization-code
          miskatonic-client-client-credentials:
            provider: spring
            client-id: miskatonic-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: books.read,faculty.read,bestiary.read
            client-name: miskatonic-client-client-credentials
        provider:
          spring:
            issuer-uri: http://auth-server:9000

miskatonic:
  base-uri: http://127.0.0.1:8090/
