server:
  port: 8090


logging:
#  pattern:
#    console: "%-5level [%thread]: %message%n"
  level:
    root: INFO
    io.sapl: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
